from colorama import Fore, Style

INFO_COLOR = Fore.CYAN + Style.BRIGHT
SUCCESS_COLOR = Fore.GREEN
FAIL_COLOR = Fore.RED + Style.BRIGHT
SKIP_COLOR = Fore.CYAN
ERROR_COLOR = Fore.YELLOW + Style.BRIGHT
RESET = Style.RESET_ALL
